import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const TermsOfService = () => (
  <div className="min-h-screen bg-background px-4 py-8">
    <div className="mx-auto max-w-3xl">
      <Link to="/">
        <Button variant="ghost" size="sm" className="mb-6">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back
        </Button>
      </Link>

      <h1 className="font-display text-3xl font-bold text-foreground mb-6">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: April 2, 2026</p>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
        <section>
          <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground">By creating an account or using CoFactor, you agree to these Terms of Service and our Privacy Policy. If you do not agree, do not use the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">2. Description of Service</h2>
          <p className="text-muted-foreground">CoFactor is a study-tracking and wellness platform for university students. It provides study logging, health-based cognitive insights, AI-generated study plans, and collaborative leaderboards.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">3. Eligibility</h2>
          <p className="text-muted-foreground">You must be at least 16 years old to use CoFactor. If you are under 18, you confirm that you have parental or guardian consent.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">4. Account Responsibilities</h2>
          <ul className="list-disc pl-6 text-muted-foreground space-y-1">
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You agree to provide accurate and current information during registration.</li>
            <li>You must not share your account with others or create multiple accounts.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">5. Acceptable Use</h2>
          <p className="text-muted-foreground">You agree not to:</p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-1">
            <li>Use the service for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to other users' data</li>
            <li>Submit false or misleading study data</li>
            <li>Interfere with or disrupt the service</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">6. Health Data Disclaimer</h2>
          <p className="text-muted-foreground">CoFactor is not a medical application. Health-based insights (cognitive readiness, burnout risk, etc.) are estimates derived from general wellness data and should not be used as medical advice. Always consult a healthcare professional for medical concerns.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">7. AI-Generated Content</h2>
          <p className="text-muted-foreground">Study plans and insights generated by AI are suggestions only. We do not guarantee their accuracy or suitability. You are responsible for your own academic decisions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">8. Intellectual Property</h2>
          <p className="text-muted-foreground">All content, design, and technology of CoFactor are owned by us. Your study data remains yours. By using the service, you grant us a limited license to process your data as described in our Privacy Policy.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">9. Account Termination</h2>
          <p className="text-muted-foreground">You may delete your account at any time from your account settings. We reserve the right to suspend or terminate accounts that violate these terms. Upon deletion, your data will be permanently erased per our Privacy Policy.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">10. Limitation of Liability</h2>
          <p className="text-muted-foreground">CoFactor is provided "as is" without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">11. Governing Law</h2>
          <p className="text-muted-foreground">These terms are governed by the laws of Italy and the European Union, including the GDPR. Disputes shall be resolved in the courts of Padova, Italy.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">12. Changes to Terms</h2>
          <p className="text-muted-foreground">We may update these terms. Continued use after changes constitutes acceptance. Material changes will be communicated via email or in-app notification.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">13. Contact</h2>
          <p className="text-muted-foreground">For questions about these Terms, contact us at <strong>legal@cofactorstudent.com</strong>.</p>
        </section>
      </div>
    </div>
  </div>
);

export default TermsOfService;
